application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.application
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
# [END libraries]
- name: jinja2
  version: latest
